version: "3.9"

services:
  dynamo:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_REGION=us-west-2
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory" ]
    volumes:
      - dynamo-data:/data

  localstack:
    image: localstack/localstack:1.3.0
    ports:
      - '4566:4566'
      - '4575:4575'
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sqs,sns,secretsmanager,s3,kinesis,lambda,iam,ssm
      - AWS_DEFAULT_REGION=us-west-2
    volumes:
      - ./infrastructure/src/main/resources/cloudformation:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: "curl --silent --fail localstack:4566/_localstack/health || exit 1"
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  api:
    image: roadlink-core-service
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        - resources=${HOME}/.gradle
    ports:
      - "8080:8080"
    environment:
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - ENVIRONMENT=cloud
    depends_on:
      dynamo:
        condition: service_started
      localstack:
        condition: service_healthy

volumes:
  dynamo-data: