version: "3.9"

services:
  localstack:
    image: localstack/localstack:1.3.0
    ports:
      - '4566:4566'
      - '4575:4575'
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=secretsmanager,dynamodb
      - AWS_DEFAULT_REGION=us-west-2
    volumes:
      - ./infrastructure/src/main/resources/cloudformation:/etc/localstack/init/ready.d
      - ./infrastructure/src/main/resources/cloudformation/user-dynamo-table.yml:/opt/code/localstack/user-dynamo-table.yml
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: "curl --silent --fail localstack:4566/_localstack/health || exit 1"
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  api:
    image: roadlink-core-service
    build:
      context: .
      dockerfile: Dockerfile
#      additional_contexts:
#        - resources=${HOME}/.gradle
    ports:
      - "8080:8080"
    environment:
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - ENVIRONMENT=cloud
    volumes:
      - C:/Users/54116/.gradle:/root/.gradle
    depends_on:
      localstack:
        condition: service_healthy
