version: "3.9"

services:
  db:
    image: mysql:8.0.0
    environment:
      MYSQL_ROOT_PASSWORD: my_password_db
      MYSQL_DATABASE: roadlink_core_db
      MYSQL_USER: my_root_user
      MYSQL_PASSWORD: my_root_password
    ports:
      - "3306:3306"

  localstack:
    image: localstack/localstack:1.3.0
    ports:
      - '4566:4566'
      - '4575:4575'
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sqs,sns,secretsmanager,s3,kinesis,lambda,iam,ssm
    volumes:
      - ./infrastructure/src/main/resources/cloudformation:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: "curl --silent --fail localstack:4566/_localstack/health | grep '\"s3\": \"running\"' | grep '\"sqs\": \"running\"' | grep '\"sns\": \"running\"'"
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s

  api:
    image: roadlink-core-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
      localstack:
        condition: service_healthy