version: "3.9"

services:
  db:
    image: mysql:8.0.0
    environment:
      MYSQL_ROOT_PASSWORD: my_password_db
      MYSQL_DATABASE: roadlink_core_db
      MYSQL_USER: my_root_user
      MYSQL_PASSWORD: my_root_password
    ports:
      - "3306:3306"
      -
  api:
    image: roadlink-core-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started