AWSTemplateFormatVersion: '2010-09-09'
Description: Ejemplo de tabla de DynamoDB con GSI en CloudFormation

Resources:
  UserDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RoadlinkCore
      AttributeDefinitions:
        - AttributeName: EntityId
          AttributeType: S
        - AttributeName: Id
          AttributeType: S
        - AttributeName: Rating
          AttributeType: N
        - AttributeName: ReceiverId
          AttributeType: S
        - AttributeName: ReviewerId
          AttributeType: S
        - AttributeName: Email
          AttributeType: S
        - AttributeName: AddressedId
          AttributeType: S
        - AttributeName: RequesterId
          AttributeType: S
      KeySchema:
        - AttributeName: EntityId
          KeyType: HASH
        - AttributeName: Id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: RatingGSI
          KeySchema:
            - AttributeName: Rating
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: RequesterIdGSI
          KeySchema:
            - AttributeName: RequesterId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: AddressedIdGSI
          KeySchema:
            - AttributeName: AddressedId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      LocalSecondaryIndexes:
        - IndexName: ReceiverIdLSI
          KeySchema:
            - AttributeName: EntityId
              KeyType: HASH
            - AttributeName: ReceiverId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: ReviewerIdLSI
          KeySchema:
            - AttributeName: EntityId
              KeyType: HASH
            - AttributeName: ReviewerId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: EmailLSI
          KeySchema:
            - AttributeName: EntityId
              KeyType: HASH
            - AttributeName: Email
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

