package com.roadlink.core.infrastructure.user

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.roadlink.core.domain.user.User
import java.util.*

@DynamoDBTable(tableName = "User")
data class UserDynamoEntity(
    /**
     * Partition key
     */
    @get:DynamoDBHashKey(attributeName = "category")
    @DynamoDBTypeConvertedEnum
    var id: UUID? = null,

    /**
     *  Sorting key
     */
    @get:DynamoDBAttribute(attributeName = "created_date")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBIndexRangeKey(localSecondaryIndexName = "created_date_idx")
    var createdDate: Date? = null,

    @get:DynamoDBAttribute(attributeName = "email")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "email")
    var email: String? = null
) {
    companion object {

        fun from(user: User): UserDynamoEntity {
            return UserDynamoEntity(
                id = user.id,
                email = user.email
            )
        }
    }
}
//    /**
//     * Local secondary index
//     */
//    @get:DynamoDBAttribute(attributeName = "title")
//    @DynamoDBRangeKey
//    var title: String


//    @get:DynamoDBAttribute(attributeName = "price")
//    @DynamoDBIndexHashKey(globalSecondaryIndexName = "price_idx")
//    var price: Double?
//


//    constructor() {
//        this.title = ""
//        this.price = null
//        this.rating = null
//        this.category = null
//        this.createdDate = null
//    }
//
//    constructor(
//        title: String,
//        category: String?,
//        createdDate: Date?,
//        price: Double?,
//        rating: Int?
//    ) {
//        this.title = title
//        this.price = price
//        this.rating = rating
//        this.category = category
//        this.createdDate = createdDate
//    }
