package com.roadlink.core.infrastructure.user

import com.amazonaws.services.dynamodbv2.datamodeling.*
import java.util.*

@DynamoDBTable(tableName = "Book")
class DynamoBook {
    // Partition key
    @get:DynamoDBHashKey(attributeName = "category")
    @DynamoDBTypeConvertedEnum
    var category: String?

    // Local secondary index
    @get:DynamoDBAttribute(attributeName = "title")
    @DynamoDBRangeKey
    var title: String

    // Sorting key
    @get:DynamoDBAttribute(attributeName = "created_date")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBIndexRangeKey(localSecondaryIndexName = "created_date_idx")
    var createdDate: Date?

    @get:DynamoDBAttribute(attributeName = "price")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "price_idx")
    var price: Double?

    @get:DynamoDBAttribute(attributeName = "rating")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "rating_idx")
    var rating: Int?

    constructor() {
        this.title = ""
        this.price = null
        this.rating = null
        this.category = null
        this.createdDate = null
    }

    constructor(
        title: String,
        category: String?,
        createdDate: Date?,
        price: Double?,
        rating: Int?
    ) {
        this.title = title
        this.price = price
        this.rating = rating
        this.category = category
        this.createdDate = createdDate
    }
}

