server:
  port: 8080
  netty:
    compression_enabled: false

cloud:
  aws:
    endpoint: http://localhost:4566
    region:
      static: us-west-2
      auto: true
    credentials:
      accessKey: key
      secretKey: secret
    stack:
      auto: false

parameter_names:
  db:
    dynamo:
      credentials: /local/roadlink-core-service/dynamo/credentials