cloud:
  aws:
    endpoint: https://dynamodb.${AWS_REGION}.amazonaws.com
    region:
      static: ${AWS_REGION}
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}