secrets:
  # define map keys in this way to allow map binding to work with unescaped characters. Check this issue out: https://github.com/spring-projects/spring-boot/issues/13404
  "[/local/roadlink-core-service/dynamo/credentials]": "{\"endpoint\":\"http://localhost:4566\", \"region\": \"us-west-2\"}"
  "[/local/roadlink-core-service/google/credentials]": "{\"client_id\":\"REPLACE_ME\"}"

parameter_names:
  db:
    dynamo:
      credentials: /local/roadlink-core-service/dynamo/credentials
  google:
    credentials: /local/roadlink-core-service/google/credentials